# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 22:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.PositiveIntegerField(unique=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(max_length=100)),
                ('lng', models.FloatField(max_length=100)),
                ('lat_lng', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, srid=4326)),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('camera_type', models.CharField(blank=True, choices=[(0, 'Non_IP'), (1, 'IP')], default='Non_IP', max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_video', models.BooleanField(default=False)),
                ('framerate', models.FloatField(blank=True, null=True)),
                ('outdoors', models.NullBooleanField()),
                ('indoors', models.NullBooleanField()),
                ('traffic', models.NullBooleanField()),
                ('inactive', models.NullBooleanField()),
                ('resolution_w', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_h', models.PositiveIntegerField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_model', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('port', models.PositiveIntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='Non_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
